sudo: required
services:
  - docker

before_install:
  - docker build -t chidambarvjoshi/docker-react -f Dockerfile.dev .

script:
  - docker run chidambarvjoshi/docker-react npm run test -- --coverage  
